version: "3.8"

services:
  backend:
    container_name: backend
    image: node:20
    tty: true
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    networks:
      - backend

  db:
    container_name: db
    image: mysql:8
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/data:/var/lib/mysql
    networks:
      - backend

volumes:
  mysql:

networks:
  backend:
