version: "3.8"

services:
  backend:
    container_name: backend
    image: node
    working_dir: /app
    tty: true
    depends_on:
      - db
    command: sh -c "npm install"
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    networks:
      - backend

  db:
    container_name: db
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
    networks:
      - backend

volumes:
  mysql:

networks:
  backend:
